# Generated by Django 4.1.13 on 2024-03-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='image',
            field=models.CharField(default='', max_length=100),
        ),
    ]
